### ISSUE TITLE
how to create objcetive statice libabary for this ?

### ISSUE THREAD

**Issue by ppatel2zc** [charlymr/IRLDocumentScanner#13]
how to create objective static library for  Document scanner. 
.a file for IRLDocumentScanner

**Comment by charlymr** [comment]
Hi,

the project include Ressources, which will not work with static library, only framework.

You could eventually remove any reference to the dependency TOCrop and drop the source code in your project or bundle everything in a framework, it should be very straigth forward.

Let me know,

Denis

**Comment by crgg** [comment]
hi, good job , how to processing the images to Threshold

**Comment by charlymr** [comment]
You should check the protocol  `IRLCameraViewProtocol` in IRLCameraView.h
[https://github.com/charlymr/IRLDocumentScanner/blob/master/Source/Private/IRLCameraView.h
](IRLCameraView.h)
this is how it is communicated .
