### ISSUE TITLE
Maintained library?

### ISSUE THREAD

**Issue by reshadf** [charlymr/IRLDocumentScanner#15]
Hi, Is this library still maintained?

**Comment by charlymr** [comment]
Hi there. Time has been missing lately for this. But I am open to pull request and will gladly give admin right if you use it in one of your project and did changes to it.

**Comment by reshadf** [comment]
Ah thanks for the answer. I will try to fork it and see if I get it to work. I usually build stuff in Swift myself so not sure if I can help with maintenance but I will give it a try!
