### ISSUE TITLE
Crashed at +[AVCaptureStillImageOutput jpegStillImageNSDataRepresentationForSurface:size:metadata:]

### ISSUE THREAD

**Issue by bhaveshbc** [charlymr/IRLDocumentScanner#16]
out fabrics report display more crash at : +[AVCaptureStillImageOutput jpegStillImageNSDataRepresentationForSurface:size:metadata:]   but while we are testing internally we are unabel to reproduce Please Help.

**Comment by charlymr** [comment]
@bhaveshbc Try and test on slower device, you may have a race condition that is not visible on an iPhone 6s/7 but is on an iPhone 5 for example. 

Without more context I can't really give more advice.  If you use Fabric you may have more insight on how the app is getting to that crash. (Do you have any "Answer" trigger that will let you analyse the user activity?)

1. Is it crashing after the first scan, second scan, etc... Could be a leak or the memory not releasing properly (Test for this, including heap growth)
2. Is it on a 32 Bit device?
3. Does it have to do with iOS11 (There are some bugs with AVFoundation introduce that will be fix in iOS11.1)

You could also send me (privately if you don't want to share code) the Symbolised crash report so I can see if I can identify anything? Finally which app are we talking about so I could test it myself, is it on the appStore?

**Comment by charlymr** [comment]
Normally the latest version should be more stable especially with OpenGL. So I believe your problem will be fix
