### ISSUE TITLE
Issue when Integrating the library Manually

### ISSUE THREAD

**Issue by chlebta** [charlymr/IRLDocumentScanner#17]
I've tried to integrate the library manually but I got this issue : 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IRLScannerViewController", referenced from:
      objc-class-ref in ScanViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any Idea how to solve it ?

**Comment by charlymr** [comment]
Sorry seeing this now. Did you get it fix? It look to me like you tried and run ARM (device code) in the simulator (X86).
I'll close the issue for now. Please let me know if you need more help
