### ISSUE TITLE
Config makes no sense

### ISSUE THREAD

**Issue by ir-fuel** [charlymr/IRLDocumentScanner#18]
What's the use of this?

```
        if (device.isFlashAvailable) {
            [device setFocusMode:AVCaptureFocusModeContinuousAutoFocus];
        }
```
IRLCameraView.m line 180

**Comment by charlymr** [comment]
@ir-fuel  You're right this is a mistake. I need to work on an update for this project. I has been on hold for a while. Apologises for this
