### ISSUE TITLE
new Crash invented after updating to pod

### ISSUE THREAD

**Issue by moontecholabs** [charlymr/IRLDocumentScanner#21]
after we have Updating pod we encounter new crash.crash details is follow

**Based on the stack trace displayed here, it looks like new calls triggering OpenGL rendering took place while the app was transitioning to, or from, a background state. If you set up OpenGL drawing in your app delegate's methods, make sure that you only did so in applicationDidBecomeActive:, never in application:willFinishLaunchingWithOptions: or application:didFinishLaunchingWithOptions:.
According to some reports, even displaying an FPS indicator for SpriteKit could cause rendering to occur before it is allowed.**

0 | libGPUSupportMercury.dylib | gpus_ReturnNotPermittedKillClient
-- | -- | --
1 | libGPUSupportMercury.dylib | gpusSubmitDataBuffers
2 | IMGSGX543RC2GLDriver | (Missing)
3 | GLEngine | gleUnbindTextureObject
4 | GLEngine | gleUnbindDeleteHashNameAndObject
5 | GLEngine | glDeleteRenderbuffersEXT_Exec
6 | GLKit | -[GLKView _deleteFramebuffer] + 142
7 | GLKit | -[GLKView dealloc] + 94
**8 | IRLDocumentScanner | -[IRLCameraView .cxx_destruct] + 244**
9 | libobjc.A.dylib | object_cxxDestructFromClass(objc_object*, objc_class*) + 116
10 | libobjc.A.dylib | objc_destructInstance + 34
11 | libobjc.A.dylib | object_dispose + 14
12 | UIKit | -[UIResponder dealloc] + 138
13 | UIKit | -[UIView dealloc] + 1576
14 | IRLDocumentScanner | -[IRLCameraView dealloc] + 154
15 | CoreFoundation | -[__NSSetI dealloc] + 128
16 | libobjc.A.dylib | objc_object::sidetable_release(bool) + 238
17 | UIKit | -[_UITraitStorageList .cxx_destruct] + 26
18 | libobjc.A.dylib | object_cxxDestructFromClass(objc_object*, objc_class*) + 116
19 | libobjc.A.dylib | objc_destructInstance + 34
20 | libobjc.A.dylib | object_dispose + 14
21 | libobjc.A.dylib | objc_object::sidetable_release(bool) + 238
22 | libobjc.A.dylib | _object_remove_assocations + 478
23 | libobjc.A.dylib | objc_destructInstance + 42
24 | libobjc.A.dylib | object_dispose + 14
25 | UIKit | -[UIResponder dealloc] + 138
26 | UIKit | -[UIView dealloc] + 1576
27 | UIKit | -[UIViewController dealloc] + 690
28 | libdispatch.dylib | _dispatch_client_callout + 22
29 | libdispatch.dylib | _dispatch_main_queue_callback_4CF + 902
30 | CoreFoundation | __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
31 | CoreFoundation | __CFRunLoopRun + 848
32 | CoreFoundation | CFRunLoopRunSpecific + 470
33 | CoreFoundation | CFRunLoopRunInMode + 104
34 | GraphicsServices | GSEventRunModal + 80
35 | UIKit | UIApplicationMain + 150
36 | iFax iOS | AppDelegate.swift line 113main
37 | libdyld.dylib | start + 2

**Comment by charlymr** [comment]
Good morning,

thanks for the report. I believe the condition may have to do with Line 692 of IRLCameraView as the dispatch is forwarded to the main queue asynchronously and therefore we could have something executed there even if the app is in the background.

``` obj-c
    dispatch_async(dispatch_get_main_queue(), ^{
        CGRect bound = weakSelf.bounds;
        // Send the Resulting Image to the Sample Buffer
        if (weakContext && weakCoreImageContext && weakGlkView != nil && CGRectIsNull(bound) == NO && weakSelf.window != nil)
        {
            [weakCoreImageContext drawImage:image inRect:bound fromRect:image.extent];
            [weakContext presentRenderbuffer:GL_RENDERBUFFER];
            [weakGlkView setNeedsDisplay];
        }
    });
```

I did a change to make sure we will not try and render anything gin case we previously got notified we will be moving to the background and the block is executed. 

@moontecholabs could you check this branch in your code and see if you can reproduce the issue?

``` bash

    pod 'IRLDocumentScanner.', :branch => 'bugfix/21', :git => 'git@github.com:charlymr/IRLDocumentScanner.git'

```

Thanks in advance,

Denis

**Comment by moontecholabs** [comment]
thanks @charlymr we will check and update soon.
