### ISSUE TITLE
Detect colors?

### ISSUE THREAD

**Issue by Alifar** [charlymr/IRLDocumentScanner#23]
Hi there,

First of all... great project you are having here.

Is there a way to detect a color? For example I only want to scan a dutch licence plate which is always yellow, see image:

![kenteken](https://user-images.githubusercontent.com/6464812/38627759-06f31640-3db0-11e8-9f61-8164a7545eac.jpg)

Thanks in advance!

**Comment by Alifar** [comment]
Example, see how AnylineOCR app does it...

![foto 11-04-18 21 42 59](https://user-images.githubusercontent.com/6464812/38639456-8a01b214-3dd1-11e8-8880-02007757f6f4.png)

**Comment by charlymr** [comment]
Hum.  Not sure my lib will do the job for you here.

My advice would be to check the new Vision framework and see if you could define the registration plate as a model.

See this for full details, I do recall seeing the ability to register images (in your case a licence plate), then ask the framework to track it.  If your intent is purely OCR on the plate, I am pretty sure you will also get what you need from vision.
**Apple Doc**
https://developer.apple.com/documentation/vision

**Here is are some good resources to see what can be done:**
https://github.com/artemnovichkov/iOS-11-by-Examples
https://github.com/vkrmchowdary/Vision-Object-Tracking
https://medium.freecodecamp.org/ios-coreml-vision-image-recognition-3619cf319d0b
https://developer.apple.com/videos/play/wwdc2017/506/

**Comment by Alifar** [comment]
Thank you for your direction 👍
