### ISSUE TITLE
framework not found IRLDocumentScanner

### ISSUE THREAD

**Issue by shaliniqsg** [charlymr/IRLDocumentScanner#25]
Hi ,

Thanks for the framework.
If I use this framework for the newly created project this feature is working fine.Without any error.
But,
We are getting the following error when we try to use it in our existing project.
ld: framework not found IRLDocumentScanner
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How to fix is error .

Thanks in Advance .
Shalini

**Comment by charlymr** [comment]
Hi,

are you sure you link it properly? And the min OS version of your project is higher or equal to the framework?

There is nothing special to this framework. 

Let me know,

Denis

**Comment by shaliniqsg** [comment]
Hi Denis,

Thanks for your reply ,

We have created the new project in that we have installed this framework using cocoa pods .

This is working fine now.

Our existing project is written in swift 2.3 but we don’t know in which Xcode version our project was created initially.
May be our project was not supporting and if we create as new project it worked for us .

Regards,
Shalini
