### ISSUE TITLE
Want to Read Color document

### ISSUE THREAD

**Issue by AnitaVPN** [charlymr/IRLDocumentScanner#28]
Hi there

As the app currently using the black and white scanning , i want it colour documnet scanning , how can i acheive thus please help to or guide me for proceed further 

> Need Help Urgently

**Comment by charlymr** [comment]
Please check the icons and methods in the api and demo. Color is supported.

**Comment by charlymr** [comment]
In the public header:
https://github.com/charlymr/IRLDocumentScanner/blob/master/Source/Public/IRLScannerViewController.h

change cameraView to IRLScannerViewTypeNormal
