### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by mobibob** [charlymr/IRLDocumentScanner#4]
I have not been able to resolve the build issues.  I am able to build the demo project, but then not able to see the difference in project setup.  I did resolve some "generic Xcode/iOS" errors when using the manual installation steps.

I have re-started the procedures multiple times and both "manual" and "automatic" install failed.

I have abandoned the "manual" steps and trying to resolve with the automatic install/build.  I have spent a considerable amount of time and hvae to move on if I cannot get some assistance.  Thanks in advance.

Here is the latest linker error (compile used to fail, but I was able to resolve the compile phase errors).

<img width="792" alt="screen shot 2016-05-20 at 8 44 32 pm" src="https://cloud.githubusercontent.com/assets/70009/15445780/8115b374-1ecc-11e6-8e42-f664013a054a.png">

**Comment by charlymr** [comment]
Hi,

can you check if somehow you are not trying to link to the Library in your project? 

It is especially true if you added the Project manually and now link using cocoapods. 

See "Linked Frameworks and Libraries" at the bottom when you select your target.

Let me know.

Denis

![screen shot 2016-05-24 at 12 29 31](https://cloud.githubusercontent.com/assets/356901/15500933/4361de90-21ab-11e6-93e2-5d71f817e29f.png)

**Comment by deucks** [comment]
I fixed this issue by removing references of IRLDocumentScanner,TOCropViewController in Framework search paths (Build settings).
Clean the build and restart xcode.
