### ISSUE TITLE
rotation issue

### ISSUE THREAD

**Issue by bhaveshbc** [charlymr/IRLDocumentScanner#9]
device :- ipad air 
countinusly  rotating device from landscap to potrait and potrait to landscap getting crash and some time stuck or black screen appear
please solve this issue for me i have integrated this dsl in my current project

**Comment by charlymr** [comment]
I updated the lib and it should not crash anymore. Please make sure you use the v. 0.2.1 of the pod. I am updating cocoapods now, so run `pod repo update`

**Comment by bhaveshbc** [comment]
ok thank you
